{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "cloudflared.fullname" . }}
  labels:
    {{- include "cloudflared.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "cloudflared.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    {{- if .Values.metrics.service.enabled }}
    - from: []
      ports:
        - protocol: TCP
          port: {{ .Values.metrics.service.port }}
    {{- end }}
  egress:
    - to: []
      ports:
        - protocol: UDP
          port: 7844
        - protocol: TCP
          port: 443
    - to:
        - namespaceSelector: {}
      ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53
{{- end }}
