{{- if not .Values.cloudflared.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cloudflared.fullname" . }}-secret
  labels:
    {{- include "cloudflared.labels" . | nindent 4 }}
type: Opaque
stringData:
  tunnelToken: {{ .Values.cloudflared.tunnelToken | default "CHANGE_ME" | quote }}
{{- end }}
