{{- if not .Values.cloudflared.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cloudflared.fullname" . }}-secret
  labels:
    {{- include "cloudflared.labels" . | nindent 4 }}
type: Opaque
stringData:
  tunnelToken: {{ required "cloudflared.tunnelToken is required when existingSecret is not set" .Values.cloudflared.tunnelToken | quote }}
{{- end }}
