apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cloudflared.fullname" . }}-secret
  labels:
    {{- include "cloudflared.labels" . | nindent 4 }}
type: Opaque
stringData:
  tunnelToken: {{ required "cloudflared.tunnelToken is required" .Values.cloudflared.tunnelToken | quote }}
