apiVersion: v2
name: cloudflared
description: Helm chart for deploying Cloudflare Tunnel (cloudflared)
type: application
version: 0.4.5
appVersion: "2026.6.0"
keywords:
  - cloudflare
  - tunnel
  - cloudflared
  - ingress
icon: https://raw.githubusercontent.com/theobs-digital/cloudflared-helm-chart/main/cloudflared/icon.png
sources:
  - https://github.com/theobs-digital/cloudflared-helm-chart
annotations:
  artifacthub.io/images: |
    - name: cloudflared
      image: cloudflare/cloudflared:2026.6.0
