apiVersion: v2
name: cloudflared
description: Helm chart for deploying Cloudflare Tunnel (cloudflared)
type: application
version: 0.4.2
appVersion: "2026.5.2"
keywords:
  - cloudflare
  - tunnel
  - cloudflared
  - ingress
icon: https://www.cloudflare.com/favicon-128.png
sources:
  - https://github.com/theobs-digital/cloudflared-helm-chart
annotations:
  artifacthub.io/images: |
    - name: cloudflared
      image: cloudflare/cloudflared:2026.5.2
