replicaCount: 2

image:
  repository: cloudflare/cloudflared
  pullPolicy: IfNotPresent
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  enabled: true
  annotations: {}
  name: "cloudflared-sa"

cloudflared:
  tunnelToken: ""

livenessProbe:
  httpGet:
    path: /ready
    port: 2000
  initialDelaySeconds: 10
  periodSeconds: 10

readinessProbe:
  httpGet:
    path: /ready
    port: 2000
  initialDelaySeconds: 5
  periodSeconds: 10

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 200m
    memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
